services:
  app:
    build: 
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - todo-network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_DATABASE=todo-app-go
      - MONGO_LOG_LEVEL=1
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  todo-network:
    driver: bridge
